### PR TITLE
fix parse of intent-filters, close #19

### LINKED ISSUE #19: Failed to parse main activity
This issues is assigned to me.

App: 天猫app  com.tmall.wireless

Decoded AndroidManifest.xml [AndroidManifest.xml.zip](https://github.com/shogo82148/androidbinary/files/2731075/AndroidManifest.xml.zip)

### PR DESCRIPTION
**Pull request by codeskyblue**

### CODE REVIEW

**Comment by codeskyblue** [comment]
image

**Comment by shogo82148** [comment]
https://github.com/pkg/errors/pull/182

support for Go 1.8 is removed in 2 days ago 😢.

I agree for removing, so will we?

**Comment by codeskyblue** [comment]
I agree to remove support for 1.3.x-1.6.x

**Comment by codeskyblue** [comment]
@shogo82148 So, what do we want to do? you decide.

**Comment by codeskyblue** [comment]
Which one will you choose? @shogo82148

**Comment by shogo82148** [comment]
ok, remove them, plz.

**Comment by codeskyblue** [comment]
done

**Comment by codeskyblue** [comment]
ping

**Comment by shogo82148** [comment]
Thanks!

LGTM!

**Pull request merged**
