### PR TITLE
support Go1.8, and drop support Go1.1

### PR DESCRIPTION
**Pull request by shogo82148**

### CODE REVIEW

**Comment by shogo82148** [comment]
tests fail on travis Go 1.8... Why??

```
ok  	github.com/shogo82148/androidbinary	0.011s
=== RUN   TestGetIcon
--- FAIL: TestGetIcon (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x684509]
goroutine 5 [running]:
testing.tRunner.func1(0xc420064ea0)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/testing/testing.go:622 +0x29d
panic(0x6d03a0, 0x88d860)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/panic.go:489 +0x2cf
github.com/shogo82148/androidbinary/apk.OpenFile(0x72db12, 0x17, 0x0, 0x865e00, 0xc420126ca0)
	/home/travis/gopath/src/github.com/shogo82148/androidbinary/apk/apk.go:47 +0x139
github.com/shogo82148/androidbinary/apk.TestGetIcon(0xc420064ea0)
	/home/travis/gopath/src/github.com/shogo82148/androidbinary/apk/apk_test.go:10 +0x4b
testing.tRunner(0xc420064ea0, 0x738c28)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/testing/testing.go:697 +0x2ca
FAIL	github.com/shogo82148/androidbinary/apk	0.007s
```

**Comment by codeskyblue** [comment]
Tested on windows go 1.8.1 test can pass.
```
λ go test -v
=== RUN   TestGetIcon
--- PASS: TestGetIcon (0.01s)
        apk_test.go:20: app label: HelloWorld
PASS
ok      github.com/codeskyblue/androidbinary/apk        0.208s
```

Maybe can be fixed by set go version to 1.8.1, not 1.8

**Comment by codeskyblue** [comment]
Also tested on linux/amd64 debian7 go 1.8.1, test passed.

**Comment by codeskyblue** [comment]
Great

**Comment by shogo82148** [comment]
The following code doesn't report any error in my environment(go version go1.8.1 darwin/amd64)... Why??

``` go
package main

import (
	"encoding/xml"
	"fmt"
)

type Elem struct {
	Attr int `xml:"attr,attr"`
}

func main() {
	var elem Elem
	xmldata := `<elem attr="@0x7F08008E"></elem>`
	fmt.Println(xml.Unmarshal([]byte(xmldata), &elem))
	fmt.Printf("%+v\n", elem)
}
```

But, Go Playground reports `strconv.ParseInt: parsing "@0x7F08008E": invalid syntax`
https://play.golang.org/p/36_S_scN_X

- Go 1.8: https://wandbox.org/permlink/A54XR4fCKlCt4KlN `<nil>`
- Go 1.7.5: https://wandbox.org/permlink/0fa7Tatb6Fc5BAVk `strconv.ParseInt: parsing "@0x7F08008E": invalid syntax`

**Comment by fujiwara** [comment]
FYI
Results of my environment are below.
```
go version go1.8 darwin/amd64 => strconv.ParseInt: parsing "@0x7F08008E": invalid syntax
go version go1.8.1 darwin/amd64 => <nil>
go version go1.7.3 linux/amd64 => <nil>
go version go1.8.1 linux/amd64 => <nil>
```

**Comment by shogo82148** [comment]
Thank you!

I found it!

- https://github.com/golang/go/issues/19333
- https://github.com/golang/go/commit/02240408a1dc47f1cdefd9695d220cf1d2fff264

```
// For Go 1.8.1 we've restored the old "no errors reported" behavior.
// We'll try again in Go 1.9 to report errors.
```

**Pull request merged**
